In [13]:
import time
import pandas as pd
import json
import gzip
import datetime
import glob


# ------------------------------------------------------------------------------

Using TensorFlow backend.

In [7]:
files = glob.glob('data/Kickstarter*json.gz')
tabletop_list = []

for file in files:
    with gzip.open(file, "rt", encoding="utf-8") as f:
        for data in f:
            entry = json.loads(data)
#             print(json.dumps(entry, indent = 4))
#             break
            if "tabletop" in entry["data"]["category"]["slug"].lower():
    #             print(entry["data"]["category"]["slug"].lower())
                try:
                    tabletop_json = {}

                    tabletop_json["game_id"] = entry["data"]["id"]
                    tabletop_json["game_name"] = entry["data"]["name"]
                    tabletop_json["game_name_slug"] = entry["data"]["slug"]
                    tabletop_json["blurb"] = entry["data"]["blurb"]
                    tabletop_json["money_goal"] = entry["data"]["goal"]
                    tabletop_json["currency_type"] = entry["data"]["current_currency"]
                    tabletop_json["date_created"] = entry["data"]["created_at"]
                    tabletop_json["date_launched"] = entry["data"]["launched_at"]
                    tabletop_json["date_obtained"] = file[17:27]
                    tabletop_json["ks_state"] = entry["data"]["state"]
                    tabletop_json["money_pledged"] = entry["data"]["pledged"]
                    tabletop_json["date_end"] = entry["data"]["deadline"]
                    tabletop_json["backers_count"] = entry["data"]["backers_count"]
                    
                    
                    tabletop_json["category_id"] = entry["data"]["category"]["id"]
                    tabletop_json["category_position"] = entry["data"]["category"]["position"]
                    tabletop_json["category_name"] = entry["data"]["category"]["name"]
                    tabletop_json["category_name_slug"] = entry["data"]["category"]["slug"]

                    tabletop_json["location_id"] = entry["data"]["location"]["id"]
                    tabletop_json["location_name"] = entry["data"]["location"]["name"]
                except:
                    print("Entry Skipped: ", entry["data"]["name"])

        #         print(json.dumps(tabletop_json, indent = 4))

                tabletop_list.append(tabletop_json)
#             break
#         break
print("games found: ", len(tabletop_list))


print(json.dumps(tabletop_list[60], indent = 4))

Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  'Reign' Enchiridion
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game
Entry Skipped:  Triumvirate Pre-Orders
Entry Skipped:  The Gentlemen of the South Sandwiche Islands
Entry Skipped:  Laugh Riot! The Comedy-Improv Card Game 11/2009
games found:  45263
{
    "game_id": 1056285448,
    "game_name": "The Original U.S. History and Path to Citizenship Game",
    "game_name_slug": "the-original-us-history-and-path-to-citizenship-ga",
    "blurb": "Educational and Fun! Learn about your government and country.\r\nHelp me fund this exciting project. Knowledge Is Power... and Fun!",
    "money_goal": 30000,
    "currency_type": "USD",
    "date_created": 1520452961,
    "date_launched": 1523318736,
    "date_obtained": "2018-05-17",
    "ks_state": "live",
    "money_pledged": 0,
    "date_end": 1528502736,
    "backers_count": 0,
    "category_id": 34,
    "category_position": 6,
    "category_name": "Tabletop Games",
    "category_name_slug": "games/tabletop games",
    "location_id": 2492259,
    "location_name": "Shelton"
}

In [8]:
tp_df = pd.DataFrame(tabletop_list)
tp_df.head()

tp_df["date_created_epoch"] = tp_df["date_created"]
tp_df["date_launched_epoch"] = tp_df["date_launched"]
tp_df["date_end_epoch"] = tp_df["date_end"]

tp_df["date_created"] = [time.strftime('%Y %m %d %H:%M:%S', time.localtime(x)) for x in tp_df.date_created]
tp_df["date_launched"] = [time.strftime('%Y %m %d %H:%M:%S', time.localtime(x)) for x in tp_df.date_launched]
tp_df["date_end"] = [time.strftime('%Y %m %d %H:%M:%S', time.localtime(x)) for x in tp_df.date_end]

tp_df["year_created"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").year for x in tp_df["date_created"]]
tp_df["month_created"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").month for x in tp_df["date_created"]]
tp_df["day_created"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").day for x in tp_df["date_created"]]
tp_df["hour_created"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").hour for x in tp_df["date_created"]]


tp_df["year_launched"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").year for x in tp_df["date_launched"]]
tp_df["month_launched"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").month for x in tp_df["date_launched"]]
tp_df["day_launched"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").day for x in tp_df["date_launched"]]
tp_df["hour_launched"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").hour for x in tp_df["date_launched"]]

tp_df["year_end"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").year for x in tp_df["date_end"]]
tp_df["month_end"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").month for x in tp_df["date_end"]]
tp_df["day_end"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").day for x in tp_df["date_end"]]
tp_df["hour_end"] = [datetime.datetime.strptime(x, "%Y %m %d  %H:%M:%S").hour for x in tp_df["date_end"]]

tp_df["year_obtained"] = [d[0:4] for d in tp_df["date_obtained"]]
tp_df["month_obtained"] = [d[5:7]  for d in tp_df["date_obtained"]]
tp_df["day_obtained"] = [d[8:10]  for d in tp_df["date_obtained"]]

tp_df.groupby("currency_type").count()
tp_df = tp_df[tp_df["currency_type"] == "USD"]
tp_df.head()

,backers_count,blurb,category_id,category_name,category_name_slug,category_position,currency_type,date_created,date_end,date_launched,...,month_launched,day_launched,hour_launched,year_end,month_end,day_end,hour_end,year_obtained,month_obtained,day_obtained
0,1045,"From Russell Kercheval, designer of the Brimst...",34,Tabletop Games,games/tabletop games,6,USD,2011 08 24 14:56:27,2011 11 01 19:00:00,2011 09 27 00:01:27,...,9,27,0,2011,11,1,19,2018,05,17
1,651,The empires are at war! Take on the role of o...,34,Tabletop Games,games/tabletop games,6,USD,2011 09 21 01:36:12,2011 11 27 11:19:00,2011 09 28 11:19:00,...,9,28,11,2011,11,27,11,2018,05,17
2,150,"Deploy your troops, claim valuable Armory card...",34,Tabletop Games,games/tabletop games,6,USD,2011 09 21 21:58:06,2011 10 28 16:04:14,2011 09 28 16:04:14,...,9,28,16,2011,10,28,16,2018,05,17
3,140,“World Conquerors” is a board & card game usin...,34,Tabletop Games,games/tabletop games,6,USD,2011 09 27 20:26:01,2011 10 28 22:23:09,2011 09 28 22:23:09,...,9,28,22,2011,10,28,22,2018,05,17
4,186,"You're alone, and you ARE going to die. It is ...",34,Tabletop Games,games/tabletop games,6,USD,2011 06 07 16:50:34,2011 11 05 01:00:38,2011 10 01 01:00:38,...,10,1,1,2011,11,5,1,2018,05,17

In [9]:
print(len(tp_df))
tp_df = tp_df.drop_duplicates(["money_pledged","game_name","backers_count"],keep="last")
tp_df = tp_df.drop_duplicates(["game_name","month_obtained"],keep="last")
print(len(tp_df))

csv_path = "data/KS_data_full" + ".csv"
print (csv_path)

tp_df.to_csv(csv_path)

43020
8431
data/KS_data_full.csv

In [11]:

tp_df = tp_df[["ks_state",
               "game_name",
               "blurb",
               "game_id",
               "money_pledged",
               "backers_count",
               "location_id",
               "money_goal",
               "month_created",
               "day_created",
               "hour_created",
               "month_launched",
               "day_launched",
               "hour_launched",
               "month_end",
               "day_end",
               "hour_end",
                "month_obtained",
               "day_obtained",
              "date_created_epoch",
              "date_launched_epoch",
              "date_end_epoch"]]

tp_df[tp_df["ks_state"] == "cancelled"].head()
tp_df.groupby("ks_state").count()
tp_df = tp_df.sort_values("date_created_epoch")
tp_df.head()

,ks_state,game_name,blurb,game_id,money_pledged,backers_count,location_id,money_goal,month_created,day_created,...,day_launched,hour_launched,month_end,day_end,hour_end,month_obtained,day_obtained,date_created_epoch,date_launched_epoch,date_end_epoch
27219,successful,"Indie Nerd Board Game, Needs Player Character ...",pictured here is the character we would like t...,1839304671,1741.02,28,2459115.0,1500,5,15,...,15,2,6,15,1,12,13,1242364202,1242369560,1245042600
27641,successful,Laugh Riot! The Comedy-Improv Card Game,"If you like to laugh, then you will love Laugh...",1124319724,1192.00,27,NaN,850,10,14,...,15,1,11,2,0,12,13,1255551799,1255584310,1257138060
27393,successful,Lines of Fire: A fantasy battle board game. (M...,"Lines of Fire: a fast-paced battle game, kicks...",694655492,535.00,26,2383144.0,350,10,22,...,1,7,9,30,23,12,13,1256252218,1283342111,1285905540
28665,successful,Laugh Riot! The Comedy-Improv Card Game 11/2009,"If you like to laugh, you will love Laugh Riot!",1629962256,52.00,2,NaN,22,11,2,...,2,11,11,17,0,12,13,1257179856,1257180459,1258434000
28101,successful,The Gentlemen of the South Sandwiche Islands,The Gentlemen of the South Sandwiche Islands i...,571386977,8936.50,151,NaN,7600,11,14,...,16,3,2,10,2,12,13,1258184967,1258360177,1265788140

In [12]:
csv_path = "data/KS_data" + ".csv"
print (csv_path)

tp_df.to_csv(csv_path)

data/KS_data.csv